//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinIOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role_Master
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Createdby { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Modifieddby { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
