//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinIOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Triage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Triage()
        {
            this.Triage_Vitals = new HashSet<Triage_Vitals>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<System.DateTime> TrgDate { get; set; }
        public Nullable<System.TimeSpan> TrgTime { get; set; }
        public Nullable<int> RiskPriority { get; set; }
        public Nullable<int> SymptomId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Triage_Vitals> Triage_Vitals { get; set; }
    }
}
